version: '3.1'

services:
  web:
    image: registry.cn-shenzhen.aliyuncs.com/lidongming/my/face-manage:6c222d8
    ports:
      - 23337:23337
    environment:
      - NGINX_LISTEN_PORT=23337
      - NGINX_SERVER_NAME=posts
      - VUE_APP_GRAPHQL_HTTP=http://39.108.107.106:4000/graphql
